# - Infrastructure:
#     - Docker Stats:
#         icon: docker.png
#         widget:
#           type: docker
#           server: my-docker # Connects the widget to the socket
#           label: System

- Media Releases:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: agenda
          maxEvents: 20
          previousDays: 3
          disableHover: true
          integrations:
            - type: sonarr
              service_group: Automation
              service_name: Sonarr
              params:
                showName: true
                showSeasonEpisode: true
                showEpisodeTitle: true

            - type: radarr
              service_group: Automation
              service_name: Radarr

# --- Media Management ---
- Media:
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://HPOmen16.local:5055
        description: Requests & Discovery
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: MTc2NzU1MjYwNTQ4MDczNWNlNTdlLTA0MGItNDZiOC1iMjgzLWU2MjJkMTYwODI5Zg==

    - Jellyfin:
        icon: jellyfin.png
        href: http://HPOmen16.local:8096
        description: Media Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: cb0d86a2f83d45cea43c91282ae990fc

# --- Downloads & Automation (Behind VPN) ---
- Automation:
    - Prowlarr:
        icon: prowlarr.png
        href: http://HPOmen16.local:9696
        widget:
          type: prowlarr
          url: http://gluetun:9696
          key: fc7f71abea9e47c8ba17774bbf4415c8

    - Radarr:
        icon: radarr.png
        href: http://HPOmen16.local:7878
        widget:
          type: radarr
          url: http://gluetun:7878 # Dashboard talks to VPN bubble
          key: 8de6cae4a8184005a63f9b445b939bc3

    - Sonarr:
        icon: sonarr.png
        href: http://HPOmen16.local:8989
        widget:
          type: sonarr
          url: http://gluetun:8989
          key: 857bb5d532be445e88a99dbe5bbe15dd

    - Lidarr:
        icon: lidarr.png
        href: http://HPOmen16.local:8686
        widget:
          type: lidarr
          url: http://gluetun:8686
          key: 2f8cae4df7ba48efb8d30a0e1216425b

- Download Client:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://HPOmen16.local:8701
        widget:
          type: qbittorrent
          url: http://qbittorrent:8701
          username: admin
          password: password
