# --- Media Management ---
- Media:
    - Jellyseerr:
        icon: jellyseerr.png
        href: http://localhost:5055
        description: Requests & Discovery
        widget:
          type: jellyseerr
          url: http://jellyseerr:5055
          key: YOUR_JELLYSEERR_API_KEY

    - Jellyfin:
        icon: jellyfin.png
        href: http://localhost:8096
        description: Media Server
        widget:
          type: jellyfin
          url: http://jellyfin:8096
          key: YOUR_JELLYFIN_API_KEY

# --- Downloads & Automation (Behind VPN) ---
- Automation:
    - Radarr:
        icon: radarr.png
        href: http://localhost:7878
        widget:
          type: radarr
          url: http://gluetun:7878 # Dashboard talks to VPN bubble
          key: YOUR_RADARR_API_KEY

    - Sonarr:
        icon: sonarr.png
        href: http://localhost:8989
        widget:
          type: sonarr
          url: http://gluetun:8989
          key: YOUR_SONARR_API_KEY

    - Prowlarr:
        icon: prowlarr.png
        href: http://localhost:9696
        widget:
          type: prowlarr
          url: http://gluetun:9696
          key: YOUR_PROWLARR_API_KEY

- Download Client:
    - qBittorrent:
        icon: qbittorrent.png
        href: http://localhost:8701
        widget:
          type: qbittorrent
          url: http://host.docker.internal:8701
          username: admin
          password: password
