layout:
  Media Releases:
    style: row
    columns: 5 # Calendar must be full width

  Utilities:
    style: row
    columns: 5 # Small utility cards

  Media:
    style: row
    columns: 3

  Automation:
    style: row
    columns: 3

  Download Client:
    style: row
    columns: 2
# --- Glance Appearance ---
# theme: dark
# color: slate
# cardBlur: none
