# widgets.yaml
- resources:
        cpu: true
        memory: true
        disk: /
        label: System Info

# - search:
#         provider: duckduckgo
#         focus: true
#         target: _blank

- datetime:
        text_size: xl
        format:
              dateStyle: long
              timeStyle: short
